sudo: false
language: ruby
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.2
  - 3.0.0
before_install: gem install bundler
gemfile:
  - gemfiles/5.0_stable.gemfile
  - gemfiles/5.1_stable.gemfile
  - gemfiles/5.2_stable.gemfile
  - gemfiles/6.0_stable.gemfile
  - gemfiles/6.1_stable.gemfile
matrix:
  exclude:
    - rvm: 2.5.8
      gemfile: gemfiles/6.1_stable.gemfile
    - rvm: 2.6.6
      gemfile: gemfiles/6.1_stable.gemfile
    - rvm: 2.7.2
      gemfile: gemfiles/6.1_stable.gemfile
    - rvm: 3.0.0
      gemfile: gemfiles/5.0_stable.gemfile
    - rvm: 3.0.0
      gemfile: gemfiles/5.1_stable.gemfile
    - rvm: 3.0.0
      gemfile: gemfiles/5.2_stable.gemfile
script:
  - bundle exec rspec
  - bundle exec rubocop
